import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import Image from "next/image";
import alplinn from "../public/dev-alp-wave.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Alparslan Korkmaz Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">ALPLINN</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-xl" />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-midnight to-[#885875] text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-midnight font-medium">
              Alparslan Korkmaz
            </h2>
            <h3 className="text-2xl py-2">Self-taught web developer.</h3>
            <p className="text-medium py-5 leading-8 text-gray-800">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit.
              Repellendus nihil libero numquam, ea error debitis vitae
              architecto illo cum. Sed minima sint repellendus quo perspiciatis
              cumque vitae nostrum amet reprehenderit.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillInstagram />
            <AiFillLinkedin />
            <AiFillTwitterCircle />
          </div>
          <div className="relative bg-gradient-to-b from-midnight to-orangejam rounded-full">
            <Image src={alplinn} />
          </div>
        </section>
      </main>
    </>
  );
}
